name: HACKEM

on:
  push:
    branches: [ dev ]
    tags:
      - '**'
  pull_request:
    branches: [ dev ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      #LUA_VERSION: 5.4.2
      #HINTS_FILE: linux.370
      HINTS_FILE: linux-debug
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: ./sys/unix/setup.sh sys/unix/hints/$HINTS_FILE
    - name: fetch lua
      run: |
        make fetch-lua
    - name: make all
      run: make all
    - name: make install
      run: make install
